  version: '3'
    
  services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - "5432:5432"
    web:
      build: .
      command: python -m flask run --host 0.0.0.0
      volumes:
        - .:/usr/src/app
      ports:
        - "5000:5000"
      depends_on:
        - db
